spring:
  datasource:
    url: jdbc:mysql://localhost:3306/novel_website
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
#mapper文件位置配置
logging:
  level:
    com.yep.controller: debug
    com.yep.service: debug
    com.yep.mapper: debug
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yep.server.pojo
  configuration:
    map-underscore-to-camel-case: true