spring:
  datasource:
    url: jdbc:mysql://localhost:3306/novel_website
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/,file:${file.dir}
#mapper文件位置配置
logging:
  level:
    com.yep.controller: debug
    com.yep.service: debug
    com.yep.mapper: debug
  file:
#    path: G:\workspace\workspace_myIdea\NovelWebsite\log
       path: /home/
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yep.server.pojo
  configuration:
    map-underscore-to-camel-case: off
file:
#  dir: G:\workspace\workspace_myIdea\NovelWebsite\file
     dir: /home/
server:
#  port: 8081
     port: 8080